import chainlit as cl
from src.utils.config import (
    DEFAULT_MODEL,
    OLLAMA_API_KEY,
    OLLAMA_BASE_URL,
)
from src.log.logger import setup_logger
from ollama import AsyncClient, ChatResponse
from typing import AsyncIterator, List, Dict

logger = setup_logger('CALL MODEL')

client = AsyncClient(
    host=OLLAMA_BASE_URL,
    headers={"Authorization": f"Bearer {OLLAMA_API_KEY}"},
)


@cl.step(name="ollama", type="tool", show_input=False)
async def call_ollama(model: str, messages: List[Dict]) -> str:
    """
    Calls the Ollama model with the provided messages and handles tool calls via MCP.
    
    Args:
        model: The name of the model to use.
        messages: The list of messages in the conversation.

    Returns:
        str: The final response generated by the model.
    """
    if not model and not messages:
        logger.error("Model name and messages are required to call Ollama.")
        raise ValueError("Model name and messages cannot be empty.")

    mcp_tools = cl.user_session.get("mcp_tools", {})
    all_tools = [tool for connection_tools in mcp_tools.values() for tool in connection_tools]
    logger.info(f"MCP All Tools: {all_tools}")
    logger.info(f"Available MCP Tools: {[tool['function']['name'] for tool in all_tools]}")
    
    try:
        while True:
            try:
                result: AsyncIterator[ChatResponse] = await client.chat(
                    model=model,
                    messages=messages,
                    tools=all_tools,
                    stream=True,
                    options={
                        'temperature': 0.01,
                        'num_ctx':512,
                    },
                )
            except Exception as e:
                logger.error(f'Error during ollama call: {e}')
                break
            
            # thinking = ''
            content = ''
            tool_calls = []
                
            async for part in result:
                if part.message.tool_calls:
                    tool_calls.extend(part.message.tool_calls)
                if part.message.content:
                    # accumulate the partial content
                    content += part.message.content
                    yield part.message.content
            
            if content != '' or len(tool_calls) > 0:
                # append the accumulated fields to the messages for the next request
                messages.append(
                    {
                        'role': 'assistant',
                        # 'thinking': thinking,
                        'content': str(content)[:2000 * 4],
                        'tool_calls': tool_calls
                    }
                )

            if tool_calls:
                tool_executed = False
                for tool_call in tool_calls:
                    tool_name = tool_call.function.name
                    tool_args = tool_call.function.arguments

                    logger.info(f"Executing tool: {tool_name}, with args: {tool_args}")

                    mcp_name = None
                    for connection_name, tools in mcp_tools.items():
                        if any(tool['function']['name'] == tool_name for tool in tools):
                            mcp_name = connection_name
                            break 
                    
                    if mcp_name:
                        try:
                            mcp_sessions = getattr(cl.context.session, 'mcp_sessions', {})
                            
                            if mcp_name in mcp_sessions:
                                mcp_session = mcp_sessions[mcp_name][0]
                                tool_result = await mcp_session.call_tool(tool_name, tool_args)
                                logger.info(f"Tool result: {str(tool_result)[:1000]}...")

                                messages.append({
                                    'role': 'tool',
                                    'content': str(tool_result)[:2000 * 4],
                                    'tool_name': tool_name
                                })
                                tool_executed = True
                            else:
                                logger.error(f'MCP session {mcp_name} not found')
                                messages.append({
                                    'role': 'tool',
                                    'content': f'MCP session {mcp_name} not found',
                                    'tool_name': tool_name
                                })
                                tool_executed = True
                        except Exception as e:
                            logger.error(f'Error calling tool {tool_name}: {e}')
                            messages.append({
                                'role': 'tool',
                                'content': f'Error calling tool {tool_name}: {e}',
                                'tool_name': tool_name
                            })
                            tool_executed = True
                    else:
                        logger.error(f'Tool {tool_name} not found in any MCP connection')
                        messages.append({
                            'role': 'tool',
                            'content': f'Tool {tool_name} not found in any MCP connection',
                            'tool_name': tool_name
                        })
                        tool_executed = True

                if not tool_executed:
                    break
            else:
                break  # No tool calls, conversation is complete
    except Exception as e:
        logger.error(f'Unexpected error during client initialization: {e}')


async def thread_renamed(thread_message: str) -> None:
    """
    Renames the thread with the given message.
    
    Args:
        thread_message (str): The new name for the thread.
    """
    if not cl.user_session.get("is_thread_renamed", False):
        messages = [
            {
                "role": "user", 
                "content": f"Summarize this query in MAX 8 words for a chat thread name: `{thread_message[:500]}`"
            }
        ]
        
        thread_name_response: ChatResponse = await client.chat(model=DEFAULT_MODEL, messages=messages)

        thread_name = thread_name_response.message.content

        await cl.context.emitter.init_thread(thread_name)
        cl.user_session.set("is_thread_renamed", True)


async def model_name(profile:str) -> str:
    """
    Returns the model name corresponding to the given profile.
    
    Args:
        profile (str): The chat profile to use.
        
    Returns:
        str: The model name to use.
    """
    model_mapping = {
        "gpt-oss:120b-cloud": "gpt-oss:120b",
        "deepseek-v3.2:cloud": "deepseek-v3.2:cloud",
        "gemma4:31b-cloud": "gemma4:31b-cloud",
        "qwen3.5:397b-cloud": "qwen3.5:397b-cloud",
        "kimi-k2.5:cloud": "kimi-k2.5:cloud",
        "glm-5.1:cloud": "glm-5.1:cloud",
        "minimax-m2.7:cloud": "minimax-m2.7:cloud",
        "mistral-large-3:675b-cloud": "mistral-large-3:675b-cloud",
    }

    if profile in model_mapping:
        return model_mapping[profile]
    else:
        # Return a default model if profile is None or not found
        logger.warning(f"Unknown chat profile: {profile}, using default model")
        return DEFAULT_MODEL


@cl.step(name="synthesize", type="tool", show_input=False)
async def synthesize_results(content:str):
    """Combine results from multiple sources into a coherent answer."""
    if not content:
        raise Exception('Content extract is extrictly required')
    
    messages = [
        {
            'role': 'system',
            'content': ("Synthesize these extract results.\n"\
                "- Combine information from multiple sources without redundancy\n"\
                "- Highlight the most relevant and actionable information\n"\
                "- Note any discrepancies between sources\n"\
                "- Keep the response concise and well-organized")
        },
        {
            'role': 'user',
            'content': content
        },
    ]
    
    try:
        result: AsyncIterator[ChatResponse] = await client.chat(
            model=DEFAULT_MODEL,
            messages=messages,
            stream=True,
            options={
                'temperature': 0.01,
                'num_ctx':512,
            },
        )

        async for part in result:
            if part.message.content:
                yield part.message.content
                
    except Exception as e:
        logger.error(f'Error during synthesize results: {e}')